CFLAGS = -g -Wall -Werror

aff : affichage.c
	gcc -o aff affichage.c

hello: hello.c
	gcc -o hello hello.c
	
q5: q5.c
	gcc -o q5 q5.c

conv1: conversion1.c
	gcc -o conv1 conversion1.c

conv2: conversion2.c
	gcc -o conv2 conversion2.c

tab: tableau.c
	gcc -o tab tableau.c
	
conc: concatenation.c
	gcc -o conc concatenation.c
	
cond: condition.c
	gcc -o cond condition.c
	
conds: conditions.c
	gcc -o conds conditions.c
	
facto: facto.c
	gcc -o facto facto.c
	
iter: iter.c
	gcc -o iter	iter.c
	
func: func.c
	gcc -o func	func.c
	
factorielle: factorielle.c
	gcc -o factorielle factorielle.c
	
sapin: sapin.c
	gcc -o sapin sapin.c
	
sapin1: sapin1.c
	gcc -o sapin1 sapin1.c
	
sapin2: sapin2.c
	gcc -o sapin2 sapin2.c
	
rand: aleatoire.c
	gcc -o rand aleatoire.c

clean:
	rm exec test.o
